### ISSUE TITLE
Device Bridge and Disconnecting Devices

### ISSUE THREAD

**Issue by JBischoff1** [iot-for-all/iotc-device-bridge#23]
I noticed a problem with the device bridge where it seems like the bridge loses the connection to my devices after some time. The bridge provisioned my devices and then I was able to see them on my Azure application. For awhile, the application would display data sent from the device and I was able to use commands to send data back to my device from Azure. After a few hours, the Azure application stopped displaying data sent from the device (sending data via command on the app still worked).

I started to see this error on the Azure logs: 
`Connection status of device changed: status = Disconnected_Retrying, reason = Communication_Error`

After some time, I started getting this message in the logs as well:
`Renewing Hub cache entries for 0 devices`

It looks like the device bridge dropped the devices from the hub and stopped listening to them. I rebuilt the device bridge and now everything seems to be working again. I was wondering if this is a common issue though and if there are any known fixes if I were to run into it again. Thanks!

**Comment by peolivei2** [comment]
Since commands were working, a connection was still active for the device in the Bridge side (messages and commands are sent over the same connection). The first message that you mentioned means that a connection was retried, usually due to a transient network error. It only becomes a problem if you see these retry messages consistently and the device can't connect, in which case you would see an actual exception in the logs after the retries expire with the underlying reason. The second message is expected.

The easiest way to investigate issues like this is having a Log Analytics workspace connected to the Bridge. If logs were being sent to Log Analytics when this issue happened, you can easily inspect the logs with the query below (replace the appropriate container name and the time filter in the second line):
```sql
ContainerInstanceLog_CL
| where TimeGenerated >= ago(1d)
| where ContainerGroup_s == "<container-group-name>"
| extend log = parse_json(Message)
| extend deviceId = tostring(log.deviceId)
| extend _message = tostring(log.message)
| where deviceId != ""
| distinct TimeGenerated, deviceId, _message
```
Multiple logs are generated when the Bridge gets a call to send a message, so you should be able to check if there were any attempts to send messages during that time and if they succeeded or failed. Alternatively, you could check the responses that you got in the application that calls the Bridge API to send the messages.

**Comment by JBischoff1** [comment]
Thanks for the information! I was able to fix my problem by rebuilding and pushing the device bridge.
